### PR TITLE
CP-918 Add codecov.io badge to readme.

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
Missing the codecov.io badge and a section about development in the readme.
#4 

## Changes
- Add codecov.io badge
- Add "Development" section to readme

## Areas of Regression
- n/a

## Testing
- n/a

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA +1, coverage is being reported correctly on the readme

Merging into master

**Comment by jayudey-wf** [comment]
@rosie run_merge_script

**Pull request merged**
