### PR TITLE
CP-2945 Adding smithy.yaml

### PR DESCRIPTION
**Pull request by jayudey-wf**
## Issue
- We needed to add a smithy.yaml for release management to more easily track dependencies.

## Changes
**Source:**
- Included smithy.yaml

**Tests:**
- n/a

## Areas of Regression
- passing CI's

## Testing
- passing CI

## Code Review
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf
@sebastianmalysa-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by charliekump-wf** [comment]
+10 CI Passes

**Comment by charliekump-wf** [comment]
Quality Review Approval: +1

- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [ ] Unit test created/updated - N/A
- [x] All unit tests pass 

Merging into master.

**Pull request merged**
