### PR TITLE
DSC-10120 - Complete transition to GHA

### PR DESCRIPTION
**Pull request by nickshoust-wf**
## Summary

Finish migration to GHA.
- Remove Dockerfile
- Remove skynet.yaml
- Generate an SBOM 

## Testing
 - CI passing
 - cyclone DX file attached as an artifact on the GHA build

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by robbecker-wf** [comment]
You can remove Dart 2.13 and 2.18 from the test matrix, and leave just Dart 2.19.6

**Review by robbecker-wf — APPROVED** [review]
+10 CI passes, cyclone file is attached, required GHA runs are set

**Comment by robbecker-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
