### PR TITLE
CP-927 Add pub badge to readme, state_machine

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
#17 

## Changes
Pub badge added to readme.

## Areas of Regression
n/a

## Testing
n/a

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by dustinlessard-wf** [comment]
Should this look like this?
screen shot 2015-08-28 at 4 05 07 pm

**Comment by evanweible-wf** [comment]
No :frowning: I see that every once in a while, the image request just times out. Just to be safe we should wait a bit on this though to see if the issue resolves itself or if it's actually a bad link

**Comment by maxwellpeterson-wf** [comment]
Looks ok now! sc

**Comment by dustinlessard-wf** [comment]
+1 (I'm just impatient!)

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA +1, badge is rendering correctly in readme

Merging into master

**Comment by jayudey-wf** [comment]
@rosie run_merge_script

**Pull request merged**
