### PR TITLE
Move to Github workflow for CI

### PR DESCRIPTION
**Pull request by evanweible-wf**
Move from Travis CI to Github workflow. Also took the opportunity to fix a lint, upgrade some deps, and use `dart format` instead of `dartfmt`.

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by evanweible-wf** [comment]
The failure on the dev channel can be ignored. We're pulling in a version of `pkg:test` prior to when they moved from `dart2js` to `dart compile js`. Once we get the latest, it will fix itself.

**Review by todbachman-wf — APPROVED** [review]

**Comment by evanweible-wf** [comment]
QA +1
- [x] CI passes (except known failure in dev channel)

@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
