### PR TITLE
CP-742 Release state_machine 2.0.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-742

JIRA and PR's included in this release: 

 CP-970  - Add helpful toString overrides for debugging  - https://github.com/Workiva/state_machine/pull/23
 CP-981  - Updating example so that close behaves the same as open and lock  - https://github.com/Workiva/state_machine/pull/27
 CP-911  - Use dart_dev for tooling, state_machine  - https://github.com/Workiva/state_machine/pull/20
 CP-918  - Add codecov.io badge to readme.  - https://github.com/Workiva/state_machine/pull/21
 CP-927  - Add pub badge to readme, state_machine  - https://github.com/Workiva/state_machine/pull/22
 CP-934  - Ampersand doesnt render on pub  - https://github.com/Workiva/state_machine/pull/25
 CP-936  - Remove unused smithy.yaml, state_machine  - https://github.com/Workiva/state_machine/pull/26

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/state_machine/compare/1.0.1...CP-742_release_2.0.0

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
What in this is causing a new major version instead of 1.0.2 or 1.1.0?

**Comment by maxwellpeterson-wf** [comment]
Nevermind I see it

+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
