### PR TITLE
CP-911 Use dart_dev for tooling, state_machine

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
Now that dart_dev is available, we should use it for tooling instead of `tool/` scripts

## Changes
**Source:**
- Run dart formatter
- Fix a couple analyzer errors

**Tests:**
- n/a

## Areas of Regression
- tooling

## Testing
- all dart_dev tasks work as expected

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
need to update the travis yaml

**Comment by evanweible-wf** [comment]
@trentgrover-wf fixed

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - dart_dev commands working as expected
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Comment by jayudey-wf** [comment]
@rosie run_merge_script

**Pull request merged**
