### PR TITLE
Wp 3756 : state_machine is now disposable

### PR DESCRIPTION
**Pull request by dustinlessard-wf**
Purpose
-------

Several stream subscriptions and stream controllers were not being correctly managed.

Solution
--------

Stream subscriptions and stream controllers are now managed.

Semantic Versioning (check one)
-------------------------------
- [ ] The following were changed in a non-backward compatible way and requires a major version bump:
  - *[link to the breaking change in the diff]*
- [ ] Something public was added or changed in backward compatible way, this requires a minor version bump
- [x] No public changes nor new features (backwards-compatible refactor or bug fix), so this can be included in a patch release

How to QA
-------
- [ ] run unit-tests
- [ ] run integration tests
- [ ] run the following related examples: main example, with [this patch](https://jira.atl.workiva.net/secure/attachment/470370/wp-3756_testing.patch).

**Required:**
@dustinlessard-wf @evanweible-wf @maxwellpeterson-wf 
@trentgrover-wf @sebastianmalysa-wf

**FYI:**
@jayudey-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
@jayudey-wf , ready for you.

**Comment by maxwellpeterson-wf** [comment]
@evanweible-wf FYI

**Comment by evanweible-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
@charliekump-wf , do you have time to QA/look at this?

**Comment by maxwellpeterson-wf** [comment]
QA +1
- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [ ] Unit tests created/updated 
- [x] All unit tests pass

Merging into master.

**Pull request merged**
