### PR TITLE
CP-724 Release state_machine 1.0.1

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-724

JIRA and PR's included in this release: 

 CP-731  - Add authors, description, and homepage to pubspec.yaml  - https://github.com/Workiva/state_machine/pull/14

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/state_machine/compare/1.0.0...CP-724_release_1.0.1

### CODE REVIEW

**Comment by ekweible** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@trentgrover-wf

**Comment by trentgrover-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
RM +1

**Pull request merged**
