### PR TITLE
WP-1030 Release state_machine 2.0.1

### PR DESCRIPTION
**Pull request by rmconsole3-wf**
Pulls Included in Release:
* [WP-3658 : added docs.yml](https://github.com/Workiva/state_machine/pull/33)
* [Wp 3756 : state_machine is now disposable](https://github.com/Workiva/state_machine/pull/34)
* [CP-1224 cleanup old scripts, state_machine](https://github.com/Workiva/state_machine/pull/29)
* [CP-2624 The codecov badge was no longer working](https://github.com/Workiva/state_machine/pull/30)
* [CP-2945 Adding smithy.yaml](https://github.com/Workiva/state_machine/pull/31)

Requested by: @dustinlessard-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/state_machine/compare/2.0.0...version-bump-state_machine-2-0-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/state_machine/compare/2.0.0...2.0.1

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinlessard-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
QA +1

- [x] Dev +1's
- [x] All unit tests pass
- [x] Rosie has run and reports properly the release the ticket will be included in
- [x] Rosie reports a clean dependency scan

Merging into master

**Pull request merged**
