### PR TITLE
CP-1224 cleanup old scripts, state_machine

### PR DESCRIPTION
**Pull request by trentgrover-wf**
## Issue
- add docs badge
- updated run of dart format
- updated to latest doc generation script
- deleted an unused test variable (dart analyze warning)

## Changes
**Source:**
- updated run of dart format (whitespace only changes)

**Tests:**
- deleted an unused test variable (dart analyze warning)

## Areas of Regression
- none

## Testing
- doc gen works as expected

## Code Review
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf 
@jayudey-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - verified that docs were still able to be generated
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Comment by teresarevious-wf** [comment]
RM +1 verified dependencies

**Pull request merged**
