### PR TITLE
CP-707 Setup Travis CI, state_machine

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- This repo is public now and Travis CI has been enabled
- Need to set up Travis CI
- #3 

## Changes
- Add .travis.yml

## Areas of Regression
- n/a

## Testing
- Travis CI build passes.

## Code Review
@trentgrover-wf
@maxwellpeterson-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
go @rmconsole-wf

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing travis build and badge added to readme
- [ ] Unit test created/updated
- [ ] All unit tests pass 

Merging into master.

**Pull request merged**
