### PR TITLE
CP-668 Release state_machine 1.0.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-668

JIRA and PR's included in this release: 

 CP-667  - Initial `state_machine` implementation  - https://github.com/Workiva/state_machine/pull/1
 CP-691  - Add changelog, state_machine  - https://github.com/Workiva/state_machine/pull/7
 CP-692  - Add Apache 2.0 license, state_machine  - https://github.com/Workiva/state_machine/pull/6
 CP-699  - Add dartfmt and analyze steps to CI build  - https://github.com/Workiva/state_machine/pull/9
 CP-707  - Setup Travis CI, state_machine  - https://github.com/Workiva/state_machine/pull/10
 CP-720  - Temporarily remove coverage dependencies, state_machine.  - https://github.com/Workiva/state_machine/pull/11

Diff Between Last Tag and Proposed Release: N/A

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
RM +1

**Comment by ericanders-wf** [comment]
+1 security

**Pull request merged**
