### PR TITLE
simplify build

### PR DESCRIPTION
**Pull request by josephswanson-wf**
- use dart image
- remove unneeded args and echo
- delete smithy.yaml (it's time)

@Workiva/app-frameworks @bradbenjamin-wf @jeffhall-wk @evanweible-wf

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by jayudey-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA +1

- [ ] Testing instruction (derived from code change)
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
  - passing CI
- [ ] Security review (if required)
- [ ] Unit tests created/updated (n/a CI change)
- [ ] All unit tests pass
- [ ] Rosie has run and reports properly the release the ticket will be included in

Merging into master.

**Comment by jayudey-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
